# Generated by Django 5.1.7 on 2025-03-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_image_date_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photograph',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
