# Generated by Django 5.1.7 on 2025-03-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
