# Generated by Django 5.1.7 on 2025-03-30 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_image_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_photograph',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
